export const PATHS = {
    HOME: "/",
    CREATE_REQUEST: "/create-request",
    REQUESTS: "/requests",
    ASSIGN_CONFIRM: "/assign-confirm",
    SURVEY_UPDATE: "/survey-update",
    CREATE_PLAN: "/create-plan",
    APPROVE_PLAN: "/approve-plan",
    ACCEPTANCE: "/acceptance",
    HISTORY: "/history",
    PERIODIC_MAINTENANCE: "/periodic-maintenance",
    EQUIPMENT_MANAGEMENT: "/equipment-management",
    CATEGORY_EQUIPMENT: "/category-equipment",
    CATEGORY_PARTS: "/category-parts",
    REPORT: "/report",
};
